
import { Geist, Geist_Mono } from "next/font/google";
import AuthGate from "./components/authGate";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body style={{ display: "flex", flexDirection: "column", margin: 0, height: "100vh" }}>
        <AuthGate>
          {children}
        </AuthGate>
      </body>
    </html>
                                                            
  )
}
