
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './components/Navbar'; // Importamos el nuevo componente
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        style={{
          display:"flex", 
          flexDirection:'column', 
          margin: 0,
          height: '100vh'
        }} 
        className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{ width: '100vw', height: 'auto' }}>
          <Navbar />
        </div>
        <main style={{ width: '100vw', flexGrow: "1", boxSizing: 'border-box' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
